# Generated by Django 3.0.3 on 2020-03-03 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_auto_20200303_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=30),
        ),
        migrations.AlterField(
            model_name='users',
            name='fiance_email',
            field=models.EmailField(max_length=30),
        ),
    ]
