# Generated by Django 3.0.3 on 2020-04-09 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_auto_20200409_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersimage',
            name='image_location',
            field=models.ImageField(upload_to='user_photos/'),
        ),
        migrations.AlterField(
            model_name='usersvideo',
            name='video_location',
            field=models.FileField(upload_to='user_videos/'),
        ),
    ]
