# Generated by Django 3.0.3 on 2020-04-09 05:47

import Users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_auto_20200409_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersvideo',
            name='video_location',
            field=models.FileField(upload_to='user_videos/', validators=[Users.validators.validate_file_size]),
        ),
    ]
