# Generated by Django 3.0.3 on 2020-04-14 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0012_auto_20200412_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogallery',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
