# Generated by Django 3.0.3 on 2020-04-14 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0013_videogallery_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videogallery',
            name='status',
        ),
        migrations.AddField(
            model_name='usersvideo',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
