# Generated by Django 3.0.3 on 2020-04-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0014_auto_20200414_0537'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='is_passed',
            field=models.BooleanField(default=False),
        ),
    ]
