# Generated by Django 3.0.3 on 2020-04-29 03:47

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0015_checklist_is_passed'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='prices',
            field=models.CharField(blank=True, max_length=70, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.AddField(
            model_name='budget',
            name='vendors',
            field=models.CharField(blank=True, max_length=70, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
