# Generated by Django 3.0.3 on 2020-05-11 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0017_remove_budget_vendors'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('amount', 'prices', 'user')},
        ),
    ]
