# Generated by Django 3.0.3 on 2020-05-14 03:38

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0018_auto_20200511_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='prices',
            field=models.CharField(blank=True, max_length=200, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
