# Generated by Django 3.0.3 on 2020-08-23 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0020_users_last_logout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='last_logout',
        ),
    ]
