# Generated by Django 3.0.3 on 2020-02-12 23:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Vendor', '0001_initial'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('notification_date', models.DateTimeField(default=datetime.datetime.now)),
                ('type', models.CharField(choices=[('Admin', 'Admin'), ('User', 'User'), ('Vendor', 'Vendor')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Users.Users')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Vendor.Vendor')),
            ],
        ),
    ]
