# Generated by Django 3.0.3 on 2020-08-23 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notification', '0002_auto_20200822_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='read_status',
            field=models.BooleanField(default=False),
        ),
    ]
