# Generated by Django 3.0.3 on 2020-03-11 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='sendor',
            field=models.CharField(blank=True, choices=[('Vendor', 'Vendor'), ('Users', 'Users')], max_length=10),
        ),
    ]
