# Generated by Django 3.0.3 on 2020-03-11 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0002_chat_sendor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='sendor',
            new_name='sender',
        ),
    ]
