# Generated by Django 3.0.3 on 2020-03-11 23:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0004_auto_20200311_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='sent_time',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
