# Generated by Django 3.0.3 on 2020-08-27 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0005_auto_20200311_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='read_staus',
            field=models.BooleanField(default=False),
        ),
    ]
