# Generated by Django 3.0.3 on 2020-08-27 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0006_chat_read_staus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='read_staus',
            new_name='read_status',
        ),
    ]
