# Generated by Django 3.0.3 on 2020-08-02 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RateandReview', '0002_auto_20200802_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='rate_value',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
