# Generated by Django 3.0.3 on 2020-02-12 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Vendor', '0001_initial'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(blank=True, max_length=30)),
                ('phonenumber', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TickedWishList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Guest.Guest')),
                ('wishlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.WishList')),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('starttime', models.TimeField()),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Guest.Guest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Users.Users')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Vendor.Vendor')),
            ],
        ),
    ]
