# Generated by Django 3.0.3 on 2020-08-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppointmentandBooking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='declined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='declined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
